Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 68, in main
    test(opt)
  File "/home/regen/Desktop/Multi-Agent-Allocation-with-Generative-Network/test.py", line 33, in test
    RL = rl(int(scale_number), mode='test')
NameError: name 'scale_number' is not defined