2021-10-07 18:13:29,436 INFO    MainThread:7325 [internal.py:wandb_internal():91] W&B internal server running at pid: 7325, started at: 2021-10-07 18:13:29.435811
2021-10-07 18:13:29,439 DEBUG   HandlerThread:7325 [handler.py:handle_request():124] handle_request: run_start
2021-10-07 18:13:29,439 INFO    WriterThread:7325 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20211007_181328-3c5b0rl5/run-3c5b0rl5.wandb
2021-10-07 18:13:30,467 DEBUG   HandlerThread:7325 [meta.py:__init__():39] meta init
2021-10-07 18:13:30,467 DEBUG   HandlerThread:7325 [meta.py:__init__():53] meta init done
2021-10-07 18:13:30,467 DEBUG   HandlerThread:7325 [meta.py:probe():210] probe
2021-10-07 18:13:30,474 DEBUG   HandlerThread:7325 [meta.py:_setup_git():200] setup git
2021-10-07 18:13:30,495 DEBUG   HandlerThread:7325 [meta.py:_setup_git():207] setup git done
2021-10-07 18:13:30,495 DEBUG   HandlerThread:7325 [meta.py:_save_pip():57] save pip
2021-10-07 18:13:30,496 DEBUG   HandlerThread:7325 [meta.py:_save_pip():71] save pip done
2021-10-07 18:13:30,496 DEBUG   HandlerThread:7325 [meta.py:_save_conda():78] save conda
2021-10-07 18:13:33,511 WARNING MainThread:7325 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-10-07 18:13:33,616 DEBUG   HandlerThread:7325 [meta.py:_save_conda():86] save conda done
2021-10-07 18:13:33,616 DEBUG   HandlerThread:7325 [meta.py:probe():252] probe done
2021-10-07 18:13:33,659 WARNING MainThread:7325 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-10-07 18:13:33,659 ERROR   MainThread:7325 [internal.py:wandb_internal():150] Internal process interrupted.
2021-10-07 18:13:34,444 INFO    SenderThread:7325 [sender.py:finish():947] shutting down sender
2021-10-07 18:13:34,659 INFO    WriterThread:7325 [datastore.py:close():288] close: output/wandb/offline-run-20211007_181328-3c5b0rl5/run-3c5b0rl5.wandb
2021-10-07 18:13:34,659 INFO    MainThread:7325 [internal.py:handle_exit():78] Internal process exited
