2021-10-13 21:01:32,878 INFO    MainThread:22667 [internal.py:wandb_internal():91] W&B internal server running at pid: 22667, started at: 2021-10-13 21:01:32.878696
2021-10-13 21:01:32,882 INFO    WriterThread:22667 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20211013_210132-27z6ajwb/run-27z6ajwb.wandb
2021-10-13 21:01:32,886 DEBUG   HandlerThread:22667 [handler.py:handle_request():124] handle_request: run_start
2021-10-13 21:01:33,803 DEBUG   HandlerThread:22667 [meta.py:__init__():39] meta init
2021-10-13 21:01:33,803 DEBUG   HandlerThread:22667 [meta.py:__init__():53] meta init done
2021-10-13 21:01:33,803 DEBUG   HandlerThread:22667 [meta.py:probe():210] probe
2021-10-13 21:01:33,809 DEBUG   HandlerThread:22667 [meta.py:_setup_git():200] setup git
2021-10-13 21:01:33,833 DEBUG   HandlerThread:22667 [meta.py:_setup_git():207] setup git done
2021-10-13 21:01:33,833 DEBUG   HandlerThread:22667 [meta.py:_save_pip():57] save pip
2021-10-13 21:01:33,834 DEBUG   HandlerThread:22667 [meta.py:_save_pip():71] save pip done
2021-10-13 21:01:33,834 DEBUG   HandlerThread:22667 [meta.py:_save_conda():78] save conda
2021-10-13 21:01:36,625 DEBUG   HandlerThread:22667 [meta.py:_save_conda():86] save conda done
2021-10-13 21:01:36,626 DEBUG   HandlerThread:22667 [meta.py:probe():252] probe done
2021-10-13 21:01:41,989 WARNING MainThread:22667 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-10-13 21:01:42,262 WARNING MainThread:22667 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-10-13 21:01:42,262 ERROR   MainThread:22667 [internal.py:wandb_internal():150] Internal process interrupted.
2021-10-13 21:01:42,662 INFO    WriterThread:22667 [datastore.py:close():288] close: output/wandb/offline-run-20211013_210132-27z6ajwb/run-27z6ajwb.wandb
2021-10-13 21:01:42,887 INFO    SenderThread:22667 [sender.py:finish():947] shutting down sender
2021-10-13 21:01:42,888 INFO    MainThread:22667 [internal.py:handle_exit():78] Internal process exited
